Add various enhancements
magicmemories/puppet-graylog_api pull request #2
Opened 2020-10-08 11:50 UTC by natlibfi-arlehiko

**Tested only with Graylog 3**

Add support for:
- Extractors
- Graylog SSO auth plugin
- Users

Fix/enhance:
- Index sets
- Roles
- Streams

2020-10-08 17:39 UTC, philomory commented
Thanks, I'll review and merge this when I get back to my office on the 12th

2020-10-12 20:00 UTC, philomory requested changes
Overall looks pretty good but I did have a few questions about the way certain things were handled.

2020-10-12 20:03 UTC, philomory commented on lib/puppet/provider/graylog_api.rb
> +  end
Also, the field filtering can be much more simply written as `params -= [:username, :password] unless @action`.

2020-10-19 12:34 UTC, natlibfi-arlehiko commented on lib/puppet/provider/graylog_index_set/graylog_api.rb
> +      creation_date: '2000-01-01T00:00:00.00Z',
'twas some development time laziness :) Fixed now.

2020-10-20 06:27 UTC, natlibfi-arlehiko commented on lib/puppet/provider/graylog_api.rb
> +  end
> Also, the field filtering can be much more simply written as `params -= [:username, :password] unless @action`.

I got `undefined method `-' for nil:NilClass (NoMethodError)` for the `-=` operator. Maybe it's supported only in newer Ruby versions or something.

2020-10-21 02:35 UTC, philomory requested changes
Just a few tiny changes left, thanks for your work on this!

2020-10-21 02:35 UTC, philomory commented on lib/puppet/provider/graylog_plugin_auth_sso/graylog_api.rb
> +        name: 'org.graylog.plugins.auth.sso/config',
```suggestion
        name: 'sso',
```

2020-10-21 02:35 UTC, philomory commented on lib/puppet/type/graylog_plugin_auth_sso.rb
> +      graylog_auth_sso_plugin_config { 'org.graylog.plugins.foo/config':
```suggestion
      graylog_auth_sso_plugin_config { 'sso':
```

2020-10-21 06:20 UTC, natlibfi-arlehiko commented
Thanks! Here you go again :)

2020-10-21 21:52 UTC, philomory approved these changes
Everything looks good to me at this point! Thanks for your help!

2020-10-21 21:53 UTC, merged

2020-10-21 21:54 UTC, philomory commented
I'll release a new version to puppet forge shortly.

2020-10-22 02:10 UTC, philomory commented
Version 0.4.0 has been released